"""src.db — Database package (split from monolithic database.py).

All public functions are re-exported here for backwards compatibility.
Usage: ``from src.db import get_conn, add_transaction, ...``
"""

# ─── core.py ──────────────────────────────────────────────────────────────────
from .core import (
    _get_table_columns,
    DB_PATH,
    CSV_PATH,
    SHARED_DB_PATH,
    set_current_user,
    get_current_user_email,
    _user_db_dir,
    _user_db_path,
    CATEGORY_TREE,
    CATEGORY_MIGRATION,
    _is_owner_user,
    get_all_categories_flat,
    CREATE_FAVOURITES_SQL,
    CREATE_CUSTOM_CATEGORIES_SQL,
    CREATE_SECRETS_SQL,
    CREATE_CUSTOM_ACCOUNTS_SQL,
    CREATE_USERS_SQL,
    CREATE_GARMIN_DAILY_SQL,
    CREATE_GARMIN_ACTIVITIES_SQL,
    CREATE_GARMIN_SLEEP_SQL,
    CREATE_GARMIN_HR_SQL,
    CREATE_GARMIN_STAGING_SQL,
    CREATE_GARMIN_BODY_COMP_SQL,
    CREATE_WITHINGS_MEASUREMENTS_SQL,
    CREATE_GUEST_INVITES_SQL,
    CREATE_FOOD_LOG_SQL,
    CREATE_AI_NOTES_SQL,
    CREATE_AI_CONTEXT_SNAPSHOTS_SQL,
    CREATE_SHOPPING_ITEMS_SQL,
    CREATE_SHOPPING_HISTORY_SQL,
    CREATE_TRANSACTIONS_SQL,
    CREATE_DAILY_LOG_SQL,
    CATEGORY_ALIASES,
    get_conn,
    get_shared_conn,
    read_sql,
    get_db_schema,
    execute_readonly_query,
    _derive_owner,
    init_shared_db,
    init_db,
    migrate_legacy_db,
    _import_csv,
)

# ─── transactions.py ──────────────────────────────────────────────────────────
from .transactions import (
    get_existing_external_ids,
    get_transactions,
    get_all_transactions,
    get_dashboard_kpi,
    get_filtered_transactions,
    add_transaction,
    get_owners,
    get_categories,
    get_years,
    delete_transaction,
    update_transaction,
    get_account_balances,
    get_recent_transactions,
    get_uah_balances,
    get_accounts,
    add_transfer,
    get_favourites,
    toggle_favourite,
    add_custom_category,
    delete_custom_category,
    rename_category,
    delete_category_and_reassign,
    get_category_frequency,
    migrate_categories,
    get_all_daily_logs,
    get_daily_log_by_date,
    upsert_daily_log,
    remove_future_transactions,
    remove_future_daily_logs,
    bulk_import_daily_logs,
    get_ai_note,
    set_ai_note,
    get_ai_note_prompt,
    set_ai_note_prompt,
    get_all_ai_notes,
    upsert_snapshot,
    get_snapshot,
    get_all_snapshots,
    get_shopping_items,
    add_shopping_item,
    add_shopping_items_bulk,
    mark_item_bought,
    mark_items_bought_bulk,
    unmark_item_bought,
    delete_shopping_item,
    clear_bought_items,
    get_shopping_history,
    get_shopping_stats,
    add_food_entry,
    get_food_log_for_date,
    get_food_summary_for_date,
    delete_food_entry,
    get_food_calories_timeseries,
    get_food_last_entry,
    export_user_data_csv,
)

# ─── auth.py ──────────────────────────────────────────────────────────────────
from .auth import (
    _secret_cache,
    _clear_secret_cache,
    get_secret,
    get_secrets,
    set_secret,
    get_user,
    upsert_user,
    has_any_users,
    get_all_users,
    add_guest_invite,
    remove_guest_invite,
    get_guest_invites,
    is_authorized_email,
    get_user_role,
    update_user_role,
    delete_user,
    save_telegram_link,
    get_telegram_link,
    get_telegram_links,
    delete_telegram_link,
    generate_telegram_connect_code,
    redeem_telegram_connect_code,
    add_audit_log,
    get_audit_log,
)

# ─── settings.py ──────────────────────────────────────────────────────────────
from .settings import (
    CREATE_SAVINGS_GOALS_SQL,
    CREATE_BUDGETS_SQL,
    CREATE_RECURRING_SQL,
    CREATE_CHAT_HISTORY_SQL,
    CREATE_BUDGET_CONFIG_SQL,
    CREATE_MANDATORY_CATEGORIES_SQL,
    get_custom_categories,
    get_custom_accounts,
    get_account_names,
    get_account_currency_map,
    add_custom_account,
    update_custom_account,
    delete_custom_account,
    get_savings_goals,
    add_savings_goal,
    update_savings_goal,
    delete_savings_goal,
    get_budgets,
    set_budget,
    delete_budget,
    get_budget_status,
    get_budget_config,
    set_budget_config,
    get_mandatory_categories,
    add_mandatory_category,
    remove_mandatory_category,
    get_avg_monthly_expenses,
    get_avg_monthly_income,
    get_current_month_income,
    calculate_weekly_budget,
    get_recurring_transactions,
    add_recurring_transaction,
    delete_recurring_transaction,
    process_recurring_transactions,
    get_chat_history,
    add_chat_message,
    clear_chat_history,
    ALL_MODULES,
    get_user_preference,
    set_user_preference,
    get_user_preferences,
    get_user_enabled_modules,
    set_user_enabled_modules,
)

__all__ = [
    # core
    "_get_table_columns", "DB_PATH", "CSV_PATH", "SHARED_DB_PATH",
    "set_current_user", "get_current_user_email", "_user_db_dir", "_user_db_path",
    "CATEGORY_TREE", "CATEGORY_MIGRATION", "_is_owner_user", "get_all_categories_flat",
    "CREATE_FAVOURITES_SQL", "CREATE_CUSTOM_CATEGORIES_SQL", "CREATE_SECRETS_SQL",
    "CREATE_CUSTOM_ACCOUNTS_SQL", "CREATE_USERS_SQL",
    "CREATE_GARMIN_DAILY_SQL", "CREATE_GARMIN_ACTIVITIES_SQL", "CREATE_GARMIN_SLEEP_SQL",
    "CREATE_GARMIN_HR_SQL", "CREATE_GARMIN_STAGING_SQL", "CREATE_GARMIN_BODY_COMP_SQL",
    "CREATE_WITHINGS_MEASUREMENTS_SQL", "CREATE_GUEST_INVITES_SQL",
    "CREATE_FOOD_LOG_SQL", "CREATE_AI_NOTES_SQL", "CREATE_AI_CONTEXT_SNAPSHOTS_SQL",
    "CREATE_SHOPPING_ITEMS_SQL", "CREATE_SHOPPING_HISTORY_SQL",
    "CREATE_TRANSACTIONS_SQL", "CREATE_DAILY_LOG_SQL", "CATEGORY_ALIASES",
    "get_conn", "get_shared_conn", "read_sql", "get_db_schema", "execute_readonly_query",
    "_derive_owner", "init_shared_db", "init_db", "migrate_legacy_db", "_import_csv",
    # transactions
    "get_existing_external_ids",
    "get_transactions", "get_all_transactions", "get_dashboard_kpi",
    "get_filtered_transactions", "add_transaction", "get_owners", "get_categories",
    "get_years", "delete_transaction", "update_transaction", "get_account_balances",
    "get_recent_transactions", "get_uah_balances", "get_accounts", "add_transfer",
    "get_favourites", "toggle_favourite", "get_custom_categories", "add_custom_category",
    "delete_custom_category", "rename_category", "delete_category_and_reassign",
    "get_category_frequency", "migrate_categories",
    "get_all_daily_logs", "get_daily_log_by_date", "upsert_daily_log",
    "remove_future_transactions", "remove_future_daily_logs", "bulk_import_daily_logs",
    "get_ai_note", "set_ai_note", "get_ai_note_prompt", "set_ai_note_prompt", "get_all_ai_notes",
    "upsert_snapshot", "get_snapshot", "get_all_snapshots",
    "get_shopping_items", "add_shopping_item", "add_shopping_items_bulk",
    "mark_item_bought", "mark_items_bought_bulk", "unmark_item_bought", "delete_shopping_item",
    "clear_bought_items", "get_shopping_history", "get_shopping_stats",
    "add_food_entry", "get_food_log_for_date", "get_food_summary_for_date",
    "delete_food_entry", "get_food_calories_timeseries", "get_food_last_entry",
    "export_user_data_csv",
    # auth
    "_secret_cache", "_clear_secret_cache", "get_secret", "get_secrets", "set_secret",
    "get_user", "upsert_user", "has_any_users", "get_all_users",
    "add_guest_invite", "remove_guest_invite", "get_guest_invites",
    "is_authorized_email", "get_user_role", "update_user_role", "delete_user",
    "save_telegram_link", "get_telegram_link", "get_telegram_links", "delete_telegram_link",
    "generate_telegram_connect_code", "redeem_telegram_connect_code",
    "add_audit_log", "get_audit_log",
    # settings
    "CREATE_SAVINGS_GOALS_SQL", "CREATE_BUDGETS_SQL", "CREATE_RECURRING_SQL",
    "CREATE_CHAT_HISTORY_SQL", "CREATE_BUDGET_CONFIG_SQL", "CREATE_MANDATORY_CATEGORIES_SQL",
    "get_custom_accounts", "get_account_names", "get_account_currency_map",
    "add_custom_account", "update_custom_account", "delete_custom_account",
    "get_savings_goals", "add_savings_goal", "update_savings_goal", "delete_savings_goal",
    "get_budgets", "set_budget", "delete_budget", "get_budget_status",
    "get_budget_config", "set_budget_config",
    "get_mandatory_categories", "add_mandatory_category", "remove_mandatory_category",
    "get_avg_monthly_expenses", "get_avg_monthly_income", "get_current_month_income",
    "calculate_weekly_budget",
    "get_recurring_transactions", "add_recurring_transaction",
    "delete_recurring_transaction", "process_recurring_transactions",
    "get_chat_history", "add_chat_message", "clear_chat_history",
    "ALL_MODULES", "get_user_preference", "set_user_preference", "get_user_preferences",
    "get_user_enabled_modules", "set_user_enabled_modules",
]
