import { NextRequest } from "next/server";
import { randomBytes } from "crypto";
import { writeFile, mkdir, access } from "fs/promises";
import { execSync } from "child_process";
import { join } from "path";

const OUTPUT_DIR = process.env.OUTPUT_DIR || "/data";

interface Config {
  language: string;
  modules: string[];
  integrations: Record<string, Record<string, string>>;
  auth: string;
  googleClientId: string;
  googleClientSecret: string;
  githubClientId: string;
  githubClientSecret: string;
  seedDemo: boolean;
}

const MODULE_ENV_FLAGS: Record<string, string> = {
  finance: "NEXT_PUBLIC_FEATURE_FINANCE",
  investments: "NEXT_PUBLIC_FEATURE_INVESTMENTS",
  health: "NEXT_PUBLIC_FEATURE_HEALTH",
  gym: "NEXT_PUBLIC_FEATURE_GYM",
  my_day: "NEXT_PUBLIC_FEATURE_MY_DAY",
  food: "NEXT_PUBLIC_FEATURE_FOOD",
  shopping: "NEXT_PUBLIC_FEATURE_SHOPPING",
  ai_chat: "NEXT_PUBLIC_FEATURE_AI_CHAT",
  ai_insights: "NEXT_PUBLIC_FEATURE_AI_INSIGHTS",
  trading: "NEXT_PUBLIC_FEATURE_TRADING",
  reporting: "NEXT_PUBLIC_FEATURE_REPORTING",
};

function generateEnv(config: Config): string {
  const lines: string[] = [
    "# Generated by PD Setup Wizard",
    `# ${new Date().toISOString()}`,
    "",
    "# Database",
    "DATABASE_URL=postgresql://pd:pd@pg:5432/pd_prod",
    "",
    "# Auth",
    `NEXTAUTH_SECRET=${randomBytes(32).toString("hex")}`,
    `ENCRYPTION_KEY=${randomBytes(32).toString("hex")}`,
    "NEXTAUTH_URL=http://localhost:3333",
  ];

  if (config.auth === "google") {
    lines.push("", "# Google OAuth");
    lines.push(`GOOGLE_CLIENT_ID=${config.googleClientId}`);
    lines.push(`GOOGLE_CLIENT_SECRET=${config.googleClientSecret}`);
  }

  if (config.auth === "github") {
    lines.push("", "# GitHub OAuth");
    lines.push(`GITHUB_CLIENT_ID=${config.githubClientId}`);
    lines.push(`GITHUB_CLIENT_SECRET=${config.githubClientSecret}`);
    lines.push(`NEXT_PUBLIC_GITHUB_AUTH_ENABLED=true`);
  }

  lines.push("", `# Auth mode`);
  lines.push(`AUTH_MODE=${config.auth}`);

  lines.push("", "# Language");
  lines.push(`NEXT_PUBLIC_LOCALE=${config.language}`);

  lines.push("", "# Feature Flags");
  for (const [moduleId, envFlag] of Object.entries(MODULE_ENV_FLAGS)) {
    lines.push(`${envFlag}=${config.modules.includes(moduleId) ? "true" : "false"}`);
  }

  lines.push("", "# Demo data");
  lines.push(`SEED_DEMO_DATA=${config.seedDemo ? "true" : "false"}`);

  // Integration keys
  const integrationKeys: string[] = [];
  for (const [, fields] of Object.entries(config.integrations)) {
    for (const [key, value] of Object.entries(fields)) {
      if (value && value.trim()) {
        integrationKeys.push(`${key}=${value.trim()}`);
      }
    }
  }
  if (integrationKeys.length > 0) {
    lines.push("", "# Integrations");
    lines.push(...integrationKeys);
  }

  lines.push("");
  return lines.join("\n");
}

function generateDockerCompose(config: Config): string {
  const useOllama = config.integrations.ai_provider?.AI_PROVIDER === "ollama";
  const useTrading = config.modules.includes("trading");

  const services: Record<string, object> = {
    "pd-app": {
      image: "ghcr.io/tarascloud/personal-dashboard:latest",
      container_name: "pd-app",
      restart: "unless-stopped",
      ports: ["3333:3333"],
      env_file: ".env",
      depends_on: { pg: { condition: "service_healthy" }, redis: { condition: "service_started" } },
      volumes: ["app-data:/app/data"],
      healthcheck: {
        test: "wget -qO- http://localhost:3333/api/health || exit 1",
        interval: "10s",
        timeout: "5s",
        retries: 5,
        start_period: "30s",
      },
    },
    pg: {
      image: "postgres:16-alpine",
      container_name: "pg",
      restart: "unless-stopped",
      environment: {
        POSTGRES_USER: "pd",
        POSTGRES_PASSWORD: "pd",
        POSTGRES_DB: "pd_prod",
      },
      volumes: ["pg-data:/var/lib/postgresql/data"],
      ports: ["5432:5432"],
      healthcheck: {
        test: "pg_isready -U pd -d pd_prod",
        interval: "5s",
        timeout: "3s",
        retries: 10,
      },
    },
    redis: {
      image: "redis:7-alpine",
      container_name: "redis",
      restart: "unless-stopped",
      volumes: ["redis-data:/data"],
    },
  };

  if (useOllama) {
    services["ollama"] = {
      image: "ollama/ollama:latest",
      container_name: "ollama",
      restart: "unless-stopped",
      volumes: ["ollama-data:/root/.ollama"],
      ports: ["11434:11434"],
    };
  }

  if (useTrading) {
    services["freqtrade"] = {
      image: "freqtradeorg/freqtrade:stable",
      container_name: "freqtrade",
      restart: "unless-stopped",
      volumes: ["./freqtrade:/freqtrade/user_data"],
      ports: ["9001:8080"],
    };
  }

  const volumes: Record<string, { driver: string }> = {
    "pg-data": { driver: "local" },
    "redis-data": { driver: "local" },
    "app-data": { driver: "local" },
  };
  if (useOllama) volumes["ollama-data"] = { driver: "local" };

  const compose = {
    services,
    volumes,
  };

  return toYaml(compose);
}

// Minimal YAML serializer (no dependencies)
function toYaml(obj: unknown, indent = 0): string {
  const pad = "  ".repeat(indent);
  if (obj === null || obj === undefined) return "null";
  if (typeof obj === "string") return obj.includes(":") || obj.includes("#") || obj.includes(" ") || obj.includes("|") ? `"${obj}"` : obj;
  if (typeof obj === "number" || typeof obj === "boolean") return String(obj);
  if (Array.isArray(obj)) {
    if (obj.length === 0) return "[]";
    return obj.map((item) => {
      if (typeof item === "object" && item !== null && !Array.isArray(item)) {
        const entries = Object.entries(item);
        const first = entries[0];
        const rest = entries.slice(1);
        let result = `${pad}- ${first[0]}: ${toYaml(first[1], indent + 2)}`;
        for (const [k, v] of rest) {
          result += `\n${pad}  ${k}: ${toYaml(v, indent + 2)}`;
        }
        return result;
      }
      return `${pad}- ${toYaml(item, indent + 1)}`;
    }).join("\n");
  }
  if (typeof obj === "object") {
    const entries = Object.entries(obj as Record<string, unknown>);
    if (entries.length === 0) return "{}";
    return entries.map(([key, value]) => {
      if (typeof value === "object" && value !== null) {
        if (Array.isArray(value) && value.every((v) => typeof v !== "object")) {
          return `${pad}${key}:\n${value.map((v) => `${pad}  - ${toYaml(v, indent + 2)}`).join("\n")}`;
        }
        return `${pad}${key}:\n${toYaml(value, indent + 1)}`;
      }
      return `${pad}${key}: ${toYaml(value, indent + 1)}`;
    }).join("\n");
  }
  return String(obj);
}

function hasDockerSocket(): boolean {
  try {
    execSync("docker info", { timeout: 5000, stdio: "pipe" });
    return true;
  } catch {
    return false;
  }
}

function waitForPostgres(log: (msg: string) => void, maxRetries = 30): boolean {
  for (let i = 0; i < maxRetries; i++) {
    try {
      execSync(
        'docker exec pg pg_isready -U pd -d pd_prod',
        { timeout: 5000, stdio: "pipe" }
      );
      return true;
    } catch {
      log(`  Waiting for PostgreSQL... (${i + 1}/${maxRetries})`);
      execSync("sleep 2");
    }
  }
  return false;
}

function runCommand(cmd: string, timeoutMs = 60000): string {
  return execSync(cmd, { timeout: timeoutMs, stdio: "pipe" }).toString();
}

export async function POST(req: NextRequest) {
  const config: Config = await req.json();

  const encoder = new TextEncoder();
  const stream = new ReadableStream({
    async start(controller) {
      const log = (msg: string) => {
        controller.enqueue(encoder.encode(msg + "\n"));
      };

      const dockerAvailable = hasDockerSocket();
      const totalSteps = dockerAvailable ? 7 : 4;
      let currentStep = 0;

      const step = (msg: string) => {
        currentStep++;
        log(`[${currentStep}/${totalSteps}] ${msg}`);
      };

      try {
        step("Generating secrets and .env file...");
        const envContent = generateEnv(config);

        step("Generating docker-compose.yml...");
        const composeContent = generateDockerCompose(config);

        step("Writing configuration files...");
        try {
          await mkdir(OUTPUT_DIR, { recursive: true });
        } catch {
          // Directory may already exist
        }

        let filesWritten = false;
        try {
          await writeFile(join(OUTPUT_DIR, ".env"), envContent, "utf-8");
          log("  -> .env written to " + join(OUTPUT_DIR, ".env"));
          await writeFile(join(OUTPUT_DIR, "docker-compose.yml"), composeContent, "utf-8");
          log("  -> docker-compose.yml written to " + join(OUTPUT_DIR, "docker-compose.yml"));
          filesWritten = true;
        } catch {
          log("  -> WARNING: Could not write to /data volume");
          log("  -> .env and docker-compose.yml content below:");
          log("");
          log("--- .env ---");
          envContent.split("\n").forEach((line) => log(line));
          log("--- end .env ---");
          log("");
          log("--- docker-compose.yml ---");
          composeContent.split("\n").forEach((line) => log(line));
          log("--- end docker-compose.yml ---");
          log("");
        }

        if (!dockerAvailable) {
          step("Docker socket not available — skipping auto-deploy.");
          log("");
          log("  To deploy manually:");
          log("  1. Save the generated files to a directory");
          log("  2. Run: docker compose up -d");
          log("  3. Run: docker exec pd-app npx prisma migrate deploy");
          if (config.seedDemo) {
            log("  4. Run: docker exec -i pg psql -U pd pd_prod < seed-demo-data.sql");
          }
          log("");
          log(`[done] Configuration generated. Mount Docker socket for auto-deploy.`);
          controller.close();
          return;
        }

        // --- Docker is available: run full deployment ---

        step("Starting containers with docker compose...");
        try {
          const output = runCommand(
            `docker compose -f ${join(OUTPUT_DIR, "docker-compose.yml")} --env-file ${join(OUTPUT_DIR, ".env")} --project-directory ${OUTPUT_DIR} up -d 2>&1`,
            120000
          );
          output.split("\n").filter(Boolean).forEach((line) => log("  " + line));
        } catch (err) {
          const msg = err instanceof Error ? err.message : "unknown error";
          log(`  ERROR: docker compose up failed: ${msg}`);
          log("");
          log("[done] Deployment failed. Check Docker logs for details.");
          controller.close();
          return;
        }

        step("Waiting for PostgreSQL to be ready...");
        const pgReady = waitForPostgres(log);
        if (!pgReady) {
          log("  ERROR: PostgreSQL did not become ready in time.");
          log("  Run manually: docker logs pg");
          log("[done] Deployment partially complete — PostgreSQL not ready.");
          controller.close();
          return;
        }
        log("  PostgreSQL is ready.");

        step("Running database migrations...");
        try {
          // Run prisma migrate deploy inside the pd-app container
          // Wait for it to be running first
          let appRunning = false;
          for (let i = 0; i < 15; i++) {
            try {
              const status = runCommand('docker inspect -f "{{.State.Running}}" pd-app');
              if (status.trim() === "true") {
                appRunning = true;
                break;
              }
            } catch {
              // container not ready yet
            }
            execSync("sleep 2");
          }

          if (!appRunning) {
            log("  WARNING: pd-app container not running yet, migrations may fail.");
          }

          const migrateOutput = runCommand(
            "docker exec pd-app npx prisma migrate deploy 2>&1",
            120000
          );
          migrateOutput.split("\n").filter(Boolean).forEach((line) => log("  " + line));
          log("  Migrations complete.");
        } catch (err) {
          const msg = err instanceof Error ? err.message : "unknown error";
          log(`  WARNING: Migration had issues: ${msg}`);
          log("  You may need to run migrations manually:");
          log("  docker exec pd-app npx prisma migrate deploy");
        }

        if (config.seedDemo) {
          step("Seeding demo data...");
          try {
            // Check if we have the seed file in the container or locally
            let seedPath = "/app/scripts/seed-demo-data.sql";
            try {
              await access(seedPath);
            } catch {
              seedPath = join(process.cwd(), "scripts", "seed-demo-data.sql");
            }

            try {
              await access(seedPath);
              const seedOutput = runCommand(
                `cat ${seedPath} | docker exec -i pg psql -U pd pd_prod 2>&1`,
                60000
              );
              const lines = seedOutput.split("\n").filter(Boolean);
              // Show summary, not every INSERT
              const insertCount = lines.filter((l) => l.startsWith("INSERT")).length;
              const errorLines = lines.filter((l) => l.includes("ERROR"));
              if (insertCount > 0) {
                log(`  Inserted ${insertCount} records.`);
              }
              if (errorLines.length > 0) {
                errorLines.forEach((l) => log("  " + l));
              }
              log("  Demo data seeded successfully.");
            } catch {
              log("  WARNING: seed-demo-data.sql not found in container.");
              log("  Seed manually: docker exec -i pg psql -U pd pd_prod < seed-demo-data.sql");
            }
          } catch (err) {
            const msg = err instanceof Error ? err.message : "unknown error";
            log(`  WARNING: Seeding had issues: ${msg}`);
          }
        } else {
          step("Skipping demo data (not selected).");
        }

        log("");
        const moduleCount = config.modules.length;
        log(`  Modules enabled: ${moduleCount}`);
        log(`  Auth mode: ${config.auth}`);
        log(`  Demo data: ${config.seedDemo ? "yes" : "no"}`);
        log("");

        // Check final container status
        try {
          const psOutput = runCommand('docker ps --format "{{.Names}}: {{.Status}}" --filter "name=pd-app" --filter "name=pg" --filter "name=redis" 2>&1');
          log("  Container status:");
          psOutput.split("\n").filter(Boolean).forEach((line) => log("    " + line));
        } catch {
          // ignore
        }

        log("");
        log("[done] Deployment complete! Your dashboard is starting at http://localhost:3333");
      } catch (err) {
        log(`ERROR: ${err instanceof Error ? err.message : "Unknown error"}`);
      } finally {
        controller.close();
      }
    },
  });

  return new Response(stream, {
    headers: {
      "Content-Type": "text/plain; charset=utf-8",
      "Transfer-Encoding": "chunked",
      "Cache-Control": "no-cache",
    },
  });
}
