import { NextRequest } from "next/server";
import { randomBytes } from "crypto";
import { writeFile, mkdir } from "fs/promises";
import { join } from "path";

const OUTPUT_DIR = "/output";

interface Config {
  language: string;
  modules: string[];
  integrations: Record<string, Record<string, string>>;
  auth: string;
  googleClientId: string;
  googleClientSecret: string;
  seedDemo: boolean;
}

const MODULE_ENV_FLAGS: Record<string, string> = {
  finance: "NEXT_PUBLIC_FEATURE_FINANCE",
  investments: "NEXT_PUBLIC_FEATURE_INVESTMENTS",
  health: "NEXT_PUBLIC_FEATURE_HEALTH",
  gym: "NEXT_PUBLIC_FEATURE_GYM",
  my_day: "NEXT_PUBLIC_FEATURE_MY_DAY",
  food: "NEXT_PUBLIC_FEATURE_FOOD",
  shopping: "NEXT_PUBLIC_FEATURE_SHOPPING",
  ai_chat: "NEXT_PUBLIC_FEATURE_AI_CHAT",
  ai_insights: "NEXT_PUBLIC_FEATURE_AI_INSIGHTS",
  trading: "NEXT_PUBLIC_FEATURE_TRADING",
  reporting: "NEXT_PUBLIC_FEATURE_REPORTING",
};

function generateEnv(config: Config): string {
  const lines: string[] = [
    "# Generated by PD Setup Wizard",
    `# ${new Date().toISOString()}`,
    "",
    "# Database",
    "DATABASE_URL=postgresql://pd:pd@pg:5432/pd_prod",
    "",
    "# Auth",
    `NEXTAUTH_SECRET=${randomBytes(32).toString("hex")}`,
    `ENCRYPTION_KEY=${randomBytes(32).toString("hex")}`,
    "NEXTAUTH_URL=http://localhost:3000",
  ];

  if (config.auth === "google") {
    lines.push("", "# Google OAuth");
    lines.push(`GOOGLE_CLIENT_ID=${config.googleClientId}`);
    lines.push(`GOOGLE_CLIENT_SECRET=${config.googleClientSecret}`);
  }

  lines.push("", `# Auth mode`);
  lines.push(`AUTH_MODE=${config.auth}`);

  lines.push("", "# Language");
  lines.push(`NEXT_PUBLIC_LOCALE=${config.language}`);

  lines.push("", "# Feature Flags");
  for (const [moduleId, envFlag] of Object.entries(MODULE_ENV_FLAGS)) {
    lines.push(`${envFlag}=${config.modules.includes(moduleId) ? "true" : "false"}`);
  }

  lines.push("", "# Demo data");
  lines.push(`SEED_DEMO_DATA=${config.seedDemo ? "true" : "false"}`);

  // Integration keys
  const integrationKeys: string[] = [];
  for (const [, fields] of Object.entries(config.integrations)) {
    for (const [key, value] of Object.entries(fields)) {
      if (value && value.trim()) {
        integrationKeys.push(`${key}=${value.trim()}`);
      }
    }
  }
  if (integrationKeys.length > 0) {
    lines.push("", "# Integrations");
    lines.push(...integrationKeys);
  }

  lines.push("");
  return lines.join("\n");
}

function generateDockerCompose(config: Config): string {
  const useOllama = config.integrations.ai_provider?.AI_PROVIDER === "ollama";
  const useTrading = config.modules.includes("trading");

  const services: Record<string, object> = {
    "pd-app": {
      image: "ghcr.io/tpedchenko/personal-dashboard:latest",
      container_name: "pd-app",
      restart: "unless-stopped",
      ports: ["3000:3000"],
      env_file: ".env",
      depends_on: ["pg", "redis"],
      volumes: ["app-data:/app/data"],
    },
    pg: {
      image: "postgres:16-alpine",
      container_name: "pg",
      restart: "unless-stopped",
      environment: {
        POSTGRES_USER: "pd",
        POSTGRES_PASSWORD: "pd",
        POSTGRES_DB: "pd_prod",
      },
      volumes: ["pg-data:/var/lib/postgresql/data"],
      ports: ["5432:5432"],
    },
    redis: {
      image: "redis:7-alpine",
      container_name: "redis",
      restart: "unless-stopped",
      volumes: ["redis-data:/data"],
    },
  };

  if (useOllama) {
    services["ollama"] = {
      image: "ollama/ollama:latest",
      container_name: "ollama",
      restart: "unless-stopped",
      volumes: ["ollama-data:/root/.ollama"],
      ports: ["11434:11434"],
    };
  }

  if (useTrading) {
    services["freqtrade"] = {
      image: "freqtradeorg/freqtrade:stable",
      container_name: "freqtrade",
      restart: "unless-stopped",
      volumes: ["./freqtrade:/freqtrade/user_data"],
      ports: ["9001:8080"],
    };
  }

  const volumes: Record<string, { driver: string }> = {
    "pg-data": { driver: "local" },
    "redis-data": { driver: "local" },
    "app-data": { driver: "local" },
  };
  if (useOllama) volumes["ollama-data"] = { driver: "local" };

  const compose = {
    version: "3.8",
    services,
    volumes,
  };

  return toYaml(compose);
}

// Minimal YAML serializer (no dependencies)
function toYaml(obj: unknown, indent = 0): string {
  const pad = "  ".repeat(indent);
  if (obj === null || obj === undefined) return "null";
  if (typeof obj === "string") return obj.includes(":") || obj.includes("#") || obj.includes(" ") ? `"${obj}"` : obj;
  if (typeof obj === "number" || typeof obj === "boolean") return String(obj);
  if (Array.isArray(obj)) {
    if (obj.length === 0) return "[]";
    return obj.map((item) => {
      if (typeof item === "object" && item !== null && !Array.isArray(item)) {
        const entries = Object.entries(item);
        const first = entries[0];
        const rest = entries.slice(1);
        let result = `${pad}- ${first[0]}: ${toYaml(first[1], indent + 2)}`;
        for (const [k, v] of rest) {
          result += `\n${pad}  ${k}: ${toYaml(v, indent + 2)}`;
        }
        return result;
      }
      return `${pad}- ${toYaml(item, indent + 1)}`;
    }).join("\n");
  }
  if (typeof obj === "object") {
    const entries = Object.entries(obj as Record<string, unknown>);
    if (entries.length === 0) return "{}";
    return entries.map(([key, value]) => {
      if (typeof value === "object" && value !== null) {
        if (Array.isArray(value) && value.every((v) => typeof v !== "object")) {
          return `${pad}${key}:\n${value.map((v) => `${pad}  - ${toYaml(v, indent + 2)}`).join("\n")}`;
        }
        return `${pad}${key}:\n${toYaml(value, indent + 1)}`;
      }
      return `${pad}${key}: ${toYaml(value, indent + 1)}`;
    }).join("\n");
  }
  return String(obj);
}

export async function POST(req: NextRequest) {
  const config: Config = await req.json();

  const encoder = new TextEncoder();
  const stream = new ReadableStream({
    async start(controller) {
      const log = (msg: string) => {
        controller.enqueue(encoder.encode(msg + "\n"));
      };

      try {
        log("[1/4] Generating secrets and .env file...");
        const envContent = generateEnv(config);

        log("[2/4] Generating docker-compose.yml...");
        const composeContent = generateDockerCompose(config);

        log("[3/4] Writing configuration files...");
        try {
          await mkdir(OUTPUT_DIR, { recursive: true });
        } catch {
          // Directory may already exist or we're not in Docker
        }

        try {
          await writeFile(join(OUTPUT_DIR, ".env"), envContent, "utf-8");
          log("  -> .env written");
        } catch {
          log("  -> .env generated (output dir not mounted — copy from logs)");
          log("");
          log("--- .env content ---");
          envContent.split("\n").forEach((line) => log(line));
          log("--- end .env ---");
          log("");
        }

        try {
          await writeFile(join(OUTPUT_DIR, "docker-compose.yml"), composeContent, "utf-8");
          log("  -> docker-compose.yml written");
        } catch {
          log("  -> docker-compose.yml generated (output dir not mounted — copy from logs)");
          log("");
          log("--- docker-compose.yml content ---");
          composeContent.split("\n").forEach((line) => log(line));
          log("--- end docker-compose.yml ---");
          log("");
        }

        const moduleCount = config.modules.length;
        log(`[4/4] Configuration complete!`);
        log("");
        log(`  Modules enabled: ${moduleCount}`);
        log(`  Auth mode: ${config.auth}`);
        log(`  Demo data: ${config.seedDemo ? "yes" : "no"}`);
        log("");
        log("[done] Files generated successfully.");
        log("Run: docker compose up -d");
      } catch (err) {
        log(`ERROR: ${err instanceof Error ? err.message : "Unknown error"}`);
      } finally {
        controller.close();
      }
    },
  });

  return new Response(stream, {
    headers: {
      "Content-Type": "text/plain; charset=utf-8",
      "Transfer-Encoding": "chunked",
      "Cache-Control": "no-cache",
    },
  });
}
